import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Page } from '@shopify/polaris';
import { ImportMinor } from '@shopify/polaris-icons';
import { InferGetStaticPropsType } from 'next';
import { NasaApiObj, NasaImageObj } from '../types/nasa-api-data';
import { getImageDataAPI } from './api/getNasaData';
import { shimmer, toBase64, updateApiDataNewProps } from '../utils';
import Video from '../components/Video';

type Props = {
  data: [] | NasaImageObj[];
};

export const getStaticProps = async () => {
  // ...
  const { json = false, status, statusText } = await getImageDataAPI();

  if (!json) {
    return {
      props: { statusText, status },
    };
  }

  const data = updateApiDataNewProps(json as NasaApiObj[]);

  return {
    props: { data }, // will be passed to the page component as props
  };
};

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({ data = [], status, statusText }) => {
  const breadcrumbs = [
    { content: 'Sample apps', url: '/sample-apps' },
    { content: 'Create React App', url: '/create-react-app' },
  ];
  const primaryAction = { content: 'New product' };
  const secondaryActions = [{ content: 'Import', icon: ImportMinor }];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page title="Polaris" breadcrumbs={breadcrumbs} primaryAction={primaryAction} secondaryActions={secondaryActions}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <div>
            {data.map(
              (
                {
                  copyright,
                  date,
                  explanation,
                  title,
                  url = 'https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png',
                  media_type,
                  thumbnail_url,
                  id,
                },
                index
              ) => {
                const blurDataURL = `data:image/svg+xml;base64,${toBase64(shimmer('336', '504'))}`;
                return (
                  <section key={id}>
                    <figure>
                      {media_type === 'video' ? (
                        <Video key={url} {...{ data, title, url, index, thumbnail_url }} />
                      ) : (
                        <Image
                          priority={index === 0 || index === 1}
                          src={url}
                          alt={title}
                          height={336}
                          width={504}
                          placeholder="blur"
                          blurDataURL={blurDataURL}
                        />
                      )}
                      <figcaption>
                        {title} :::: {date}
                      </figcaption>
                      <p>{explanation}</p>
                      <sub>{copyright}</sub>
                    </figure>
                  </section>
                );
              }
            )}
          </div>

          <p className={styles.description}>
            Get started by editing <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
            </a>
          </div>
        </main>
      </Page>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
